Fix for TypeError: get_torch_device_name() missing 1 required positional argument:'device'. Also convert 'torch.device' object to string to prevent error when decoding to str.